version: '3.8'
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=True
    command: python3 manage.py runserver 0.0.0.0:8000

    container_name: django-first-app
  
